name: Deploy to GitHub pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      BUILD_PATH: 'build'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - run: yarn build

      - name: Deploy Build & Results to Github Pages 
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ env.BUILD_PATH }}